spring.application.name=quiz-service
server.port=${PORT:8081}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/quiz_service}

# JWT — same secret from the RECALL-API
jwt.secret=${JWT_SECRET:fZOMG1sttJumrgaZOt2aPwCFLe8cdMxnoZrHFTyOI6w}

# RECALL API
recall.api.url=${RECALL_API_URL:https://language-learning-api-qe0e.onrender.com}