spring.application.name=quiz-service
server.port=${PORT:8081}

# MongoDB
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://dmytrodevshyshkin_db_user:VoOPAuTtKt6OFAZ7@recallpractice.xvebbf3.mongodb.net/?appName=RecallPractice}
spring.mongodb.uuid-representation=standard

# JWT — same secret from the RECALL-API
jwt.secret=${JWT_SECRET:9cf630d31ce4f9e3548bad08f3c5b52891418cb0e80adff6c29d26a5726ce775}

# RECALL API
recall.api.url=${RECALL_API_URL:https://language-learning-api-qe0e.onrender.com}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:PLAIN}

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME}' password='${KAFKA_PASSWORD}';

spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:main-backend}
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.certificates=${KAFKA_CA_CERT}
spring.kafka.properties.ssl.truststore.location=classpath:ca.pem