spring.application.name=quiz-service
server.port=${PORT:8081}

# MongoDB
spring.data.mongodb.uri=mongodb+srv://dmytrodevshyshkin_db_user:VoOPAuTtKt6OFAZ7recallpractice.xvebbf3.mongodb.net/?appName=RecallPractice
spring.data.mongodb.uuid-representation=standard

# JWT — same secret from the RECALL-API
jwt.secret=${JWT_SECRET:9cf630d31ce4f9e3548bad08f3c5b52891418cb0e80adff6c29d26a5726ce775}

# RECALL API
recall.api.url=${RECALL_API_URL:https://language-learning-api-qe0e.onrender.com}

# Kafka - Confluent Cloud
spring.kafka.bootstrap-servers=pkc-nq356.eu-south-2.aws.confluent.cloud:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME:44OLPMW6HVKC7BMG}' password='${KAFKA_PASSWORD:cfltwIB8Wv/z3XfoZEmtuw8Q0mRkZBP9csfAPGLXDQVQy9Q/N8wnMaeLafRBmdew}';
spring.kafka.properties.session.timeout.ms=45000
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer